### ISSUE TITLE
Update Ruby to 2.4

### ISSUE THREAD

**Issue by yachub** [genebean/cent7runner#1]
May I request that the Docker image be updated from Ruby 2.0 to 2.4?

I am using this image for continuous integration tests with Puppet 5 and receive the following error when using the `puppet 5.0.0` gem:

```
bundle exec rake tests
/usr/share/gems/gems/bundler-1.7.8/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /builds/puppet-config/control in PATH, mode 040777
---> syntax:manifests
Support for ruby version 2.0.0 is deprecated and will be removed in a future release. See https://docs.puppet.com/puppet/latest/system_requirements.html#ruby for a list of supported ruby versions.
   (at /builds/puppet-config/control/vendor/ruby/gems/puppet-5.0.0/lib/puppet.rb:181:in `<module:Puppet>')
ERROR: Job failed: exit code 1
```

Thanks,

**Comment by genebean** [comment]
Sure! Any reason not to go on up to 2.4?

**Comment by yachub** [comment]
I can't think of any reason why not!

**Comment by yachub** [comment]
Actually, now that I think about it I can't think of any reason not to just use the `centos-7-rvm-multi` image.

Plus, I imagine this would be better for you since its one less image to maintain and you already have them built using packer. Hope you haven't put too much work into it yet!

**Comment by genebean** [comment]
If that works for you it certainly works for me. Shall we keep this open or close it?

**Comment by yachub** [comment]
I'll go ahead and close.

Thanks,

**Comment by yachub** [comment]
@genebean had a brilliant thought of some kind. Reopening!

**Comment by yachub** [comment]
Well never mind, as it turns out https://hub.docker.com/r/centos/ruby-24-centos7/ was able to solve my problem perfectly out of the box without any modification.

Thanks,
